kind: Deployment
apiVersion: apps/v1
metadata:
  name: javaapp
spec:
  replicas: 10
  minReadySeconds: 45 # wait for 45 sec before going to deploy next pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 2        # max number of pods to run for the deployment
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      name: javaapp
      labels:
        app: javaapp
    spec:
      containers:
       - name: app
         image: kaushik0656m21/javaapp:$BUILD_NUMBER
        
---
kind: Service
apiVersion: v1
metadata:
   name: javaapp-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector: 
    app: javaapp
